import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import { TopCategories } from '@/components/top-categories'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='flex  flex-col h-lvh justify-between '>
					{' '}
					<Navbar />{' '}
					<div className=' border border-red-700 flex justify-center relative align-start'>
						{children}
						<div className='absolute right-48 top-56 mt-16 '>
							Top Categories <TopCategories />
						</div>
					</div>
					{/* <div className='flex justify-center'>
						<Footer />
					</div> */}
				</div>
			</body>
		</html>
	)
}
