import type { Metadata } from 'next'
import { Fira_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
const fira = Fira_Mono({
	weight: ['400', '500', '700'],
	subsets: ['latin-ext'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={fira.className}>
				<div className='flex  flex-col h-full justify-between '>
					{' '}
					<Navbar />{' '}
					<div className='  flex justify-center relative align-start pb-12'>
						{children}
						{/* <span className='absolute  right-56 m-16 top-64'>
							Top Categories
						</span>{' '}
						<div className='absolute right-48 top-72 mt-16 '>
							<TopCategories />
						</div> */}
					</div>
					{/* <div className='flex justify-center'>
						<Footer />
					</div> */}
				</div>
				{/* <div className=' circle fixed right-48 bottom-12 mt-16'>
					{/* generate a circle with letter B */}
				{/* Put the characters Contact around this circle 

					<div className='rounded-full'>
						Contact &nbsp;&nbsp;●&nbsp;&nbsp; Contact
					</div>
					<svg
						width='100'
						height='100'
						viewBox='0 0 100 100'
						xmlns='http://www.w3.org/2000/svg'
					>
						<circle cx='50' cy='50' r='50' fill='black' />
						<text
							x='50%'
							y='50%'
							dy='.3em'
							textAnchor='middle'
							fill='white'
							fontSize='3em'
							fontFamily='Arial'
						>
							B
						</text>
					</svg>
				</div> */}
			</body>
		</html>
	)
}
