import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer/Footer'
import Navbar from '@/components/Navbar/Navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='flex flex-col h-lvh justify-between'>
					{' '}
					<Navbar />{' '}
					<div className='w-[60%] flex justify-center m-auto p-auto align-start'>
						{children}
					</div>
					<div className='flex justify-center'>
						<Footer />
					</div>
				</div>
			</body>
		</html>
	)
}
